### ISSUE TITLE
After server crash, player's inventory is gone

### ISSUE THREAD

**Issue by Tuchan** [Block2Block/HubParkour#26]
If a player starts the parkour and the server crashes, player's inventory is wiped when they join.

Version: `2.6.9`

**Comment by Block2Block** [comment]
Apologies for such a late reply, due to the way that the inventory is stored while the player is in the parkour, there isn't really much I can do about it as it is stored in memory, not on disk so is not strictly speaking a bug. The only thing I can suggest is disabling it if your server is prone to crashing.
